---
# tasks file for haproxy
- name: install haproxy
  package:
          name: haproxy
          state: present  

- name: copy haproxy.cfg
  template:
          src: "haproxy.cfg"
          dest: "/etc/haproxy/haproxy.cfg"

  notify: changed conf file

- name: start haproxy
  service:
          name: "haproxy"
          state: started  
